import {
  pro1,
  pro10,
  pro11,
  pro12,
  pro13,
  pro14,
  pro15,
  pro16,
  pro17,
  pro18,
  pro19,
  pro2,
  pro3,
  pro4,
  pro5,
  pro6,
  pro7,
  pro8,
  pro9,
} from "../pic/img";

const getData = () => {
  fetch("https://api.escuelajs.co/api/v1/products")
    .then((res) => res.json())
    .then((error) => error.messages);
};

export const dataToys = [
  {
    name: "Consectetur Hampden",
    price: 83.89,
    id: 1,
    quantity: 1,
    pic: `${pro1}`,
  },
  {
    name: "Exercitat Virginia",
    price: 87,
    id: 2,
    quantity: 1,
    pic: `${pro2}`,
  },
  {
    name: "Laborum eveniet",
    price: 93.03,
    id: 3,
    quantity: 1,
    pic: `${pro3}`,
  },
  {
    name: "Nostrud exercitation",
    price: 93.0,
    id: 4,
    quantity: 1,
    pic: `${pro4}`,
  },
  {
    name: "Voluptates repudiandae",
    price: 105,
    id: 5,
    quantity: 1,
    pic: `${pro5}`,
  },
  {
    name: "Praesentium voluptatum",
    price: 105,
    id: 6,
    quantity: 1,
    pic: `${pro6}`,
  },
  {
    name: "Consectetur Hampden",
    price: 70.0,
    id: 7,
    quantity: 1,
    pic: `${pro7}`,
  },
  {
    name: "Exercitat Virginia",
    price: 63.0,
    id: 8,
    quantity: 1,
    pic: `${pro8}`,
  },
  {
    name: "Voluptas assumenda",
    price: 78.0,
    id: 9,
    quantity: 1,
    pic: `${pro9}`,
  },
  {
    name: "Voluptates repudiandae",
    price: 54.05,
    id: 10,
    quantity: 1,
    pic: `${pro10}`,
  },
  {
    name: "Voluptas assumenda",
    price: 78.0,
    id: 11,
    quantity: 1,
    pic: `${pro11}`,
  },
  {
    name: "Praesentium voluptatum",
    price: 89.0,
    id: 12,
    quantity: 1,
    pic: `${pro12}`,
  },
  {
    name: "Consectetur Hampden",
    price: 95,
    id: 13,
    quantity: 1,
    pic: `${pro13}`,
  },
  {
    name: "Exercitat Virginia",
    price: 115,
    id: 14,
    quantity: 1,
    pic: `${pro14}`,
  },
  {
    name: "Laborum eveniet",
    price: 93.6,
    id: 15,
    quantity: 1,
    pic: `${pro15}`,
  },
  {
    name: "Consectetur Hampden",
    price: 35,
    id: 16,
    quantity: 1,
    pic: `${pro16}`,
  },
  {
    name: "Laborum eveniet",
    price: 97.05,
    id: 17,
    quantity: 1,
    pic: `${pro17}`,
  },
  {
    name: "Exercitat Virginia",
    price: 87,
    id: 18,
    quantity: 1,
    pic: `${pro18}`,
  },
  {
    name: "Nostrud exercitation",
    price: 93.0,
    id: 19,
    quantity: 1,
    pic: `${pro19}`,
  },
];
